### ISSUE TITLE
cryptomator no longer started, new install fails with same error

### ISSUE THREAD

**Issue by gitmeED331** [cryptomator/aur#3]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

cryptomator stopped running, then failed to update or install with same error

### What software is involved?

- Operating System: Arch Linux
- kernel: Linux 6.6.18-1-lts x86_64
- Cryptomator: no longer installed, unable to reinstall due to error

### Volume Type

None

### Steps to Reproduce

1. attempt to install by any method (maven, pkgbuild/makepkg, YAY), fails to build package with the exact same error at the exact same point.

### Expected Behavior

install to complete without error and run without error.

### Actual Behavior

fails to open/run
fails to build/install

### Reproducibility

Always

### Relevant Log Output

```shell
jdk-21.0.2+13/NOTICE
Archive:  openjfx.zip
  inflating: jmods/javafx.graphics.jmod  
  inflating: jmods/javafx.controls.jmod  
  inflating: jmods/javafx.fxml.jmod  
  inflating: jmods/javafx.base.jmod  
Picked up _JAVA_OPTIONS: ’-Dswing.aatext=TRUE -Dawt.useSystemAAFontSettings=on’
Unrecognized option: ’-Dswing.aatext=TRUE
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: cryptomator-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
cryptomator - exit status 4
```

### Anything else?

I have tried uninstalling all dependencies and doing a fresh install, nothing seems to solve.
Tried installing previous versions, same error.

**Comment by SailReal** [comment]
Can you please open a terminal and enter `echo $JAVA_OPTIONS` . What is the output?

**Comment by gitmeED331** [comment]
> Can you please open a terminal and enter `echo $_JAVA_OPTIONS` . What is the output?

’-Dswing.aatext=TRUE -Dawt.useSystemAAFontSettings=on’

**Comment by gitmeED331** [comment]
Okay, okay... so, I'm blind and stupid, the answer is in the error.

Now, I have to figure out what install made that change and whether anything else will be messed up without that string.

Thank you for entertaining my simpleness.
